[tools]
rojo = "rojo-rbx/rojo@7.3.0"
selene = "Kampfkarren/selene@0.26.1"
stylua = "JohnnyMorganz/StyLua@0.19.1"
darklua = "seaofvoices/darklua@0.13.1"
wally-package-types = "johnnymorganz/wally-package-types@1.3.1"