name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]

jobs:
  styling:
    name: styling
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Install aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: .

  testing:
    name: testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Install luau
        uses: encodedvenom/install-luau@v4.2
        with:
          version: "0.651"

      - name: Run tests
        run: |
          for file in tests/*.spec.luau; do
            luau $file
          done
